In [1]:
import pandas as pd
import numpy as np
import scipy
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn import preprocessing
from sklearn.metrics import classification_report

In [2]:
draftwithcollege = pd.read_csv('CollegeRookieStats_TeamRanksAdd.csv')
stats = pd.read_csv('CollegeRookieStats.csv')
standard = pd.read_csv('CollegeRookieStats_standardized.csv')

In [3]:
standard

Unnamed: 0   ID             Name       College NBATeam  DraftYear  \
0             1    1    Kenyon Martin    Cincinnati     NJN       2000   
1             2    2   Stromile Swift           LSU     VAN       2000   
2             3    3     Marcus Fizer    Iowa State     CHI       2000   
3             4    4      Mike Miller       Florida     ORL       2000   
4             5    5  DerMarr Johnson    Cincinnati     ATL       2000   
..          ...  ...              ...           ...     ...        ...   
631         632  632      Jordan Bone     Tennessee     NOP       2019   
632         633  633         Miye Oni          Yale     GSW       2019   
633         634  634      Cam Reddish          Duke     ATL       2019   
634         635  635   Kevin PorterJr           USC     MIL       2019   
635         636  636        Ja Morant  Murray State     MEM       2019   

     DraftPick         G        MP        FG  ...    NBAAST    NBASTL  NBABLK  \
0            1  0.755102  0.562874  0.436782  ...  0.218391  0.500000    0.68   
1            2  0.306122  0.649701  0.517241  ...  0.045977  0.363636    0.40   
2            4  0.625850  0.838323  0.747126  ...  0.126437  0.181818    0.12   
3            5  0.408163  0.652695  0.448276  ...  0.195402  0.272727    0.08   
4            6  0.183673  0.676647  0.436782  ...  0.091954  0.272727    0.16   
..         ...       ...       ...       ...  ...       ...       ...     ...   
631         57  0.612245  0.634731  0.344828  ...  0.000000  0.000000    0.00   
632         58  0.557823  0.802395  0.528736  ...  0.000000  0.000000    0.00   
633         10  0.210884  0.742515  0.425287  ...  0.000000  0.000000    0.00   
634         30  0.108844  0.514970  0.333333  ...  0.000000  0.000000    0.00   
635          2  0.408163  0.910180  0.632184  ...  0.000000  0.000000    0.00   

       NBAPTS  DraftRange  Pos.C  Pos.PF  Pos.PG  Pos.SF  Pos.SG  
0    0.533333    1.000000      0       1       0       0       0  
1    0.217778    1.000000      0       1       0       0       0  
2    0.422222    1.000000      0       1       0       0       0  
3    0.528889    1.000000      0       0       0       1       0  
4    0.226667    1.000000      0       0       0       1       0  
..        ...         ...    ...     ...     ...     ...     ...  
631  0.000000    0.166667      0       0       1       0       0  
632  0.000000    0.166667      0       0       0       0       1  
633  0.000000    1.000000      0       0       0       0       1  
634  0.000000    0.666667      0       0       0       0       1  
635  0.000000    1.000000      0       0       1       0       0  

[636 rows x 40 columns]

In [4]:
stats.isnull().sum()

Unnamed: 0    0
Name          0
School        0
G             0
MP            0
FG            0
FGA           0
FG%           0
2P            0
2PA           0
2P%           0
3P            0
3PA           0
3P%           0
FT            0
FTA           0
FT%           0
TRB           0
AST           0
STL           0
BLK           0
TOV           0
PF            0
PTS           0
SOS           0
NBATRB        0
NBAAST        0
NBASTL        0
NBABLK        0
NBAPTS        0
Pk            0
Tm            0
Year          0
Pos           0
dtype: int64

In [5]:
draftwithcollege.head(20)

ID                      Name        College NBATeam  DraftYear  \
0   587           Zion Williamson           Duke     NOP       2019   
1   588                RJ Barrett           Duke     NYK       2019   
2   589            DeAndre Hunter       Virginia     LAL       2019   
3   590            Darius Garland     Vanderbilt     CLE       2019   
4   591            Jarrett Culver     Texas Tech     PHO       2019   
5   592                Coby White            UNC     CHI       2019   
6   593              Jaxson Hayes          Texas     ATL       2019   
7   594             Rui Hachimura        Gonzaga     WAS       2019   
8   595           Cameron Johnson    Texas State     MIN       2019   
9   596             PJ Washington       Kentucky     CHO       2019   
10  597               Tyler Herro       Kentucky     MIA       2019   
11  598            Romeo Langford        Indiana     BOS       2019   
12  599               Chuma Okeke         Auburn     ORL       2019   
13  600  Nickeil Alexander-Walker  Virginia Tech     BRK       2019   
14  601          Matisse Thybulle     Washington     BOS       2019   
15  602            Brandon Clarke        Gonzaga     OKC       2019   
16  603            Grant Williams      Tennessee     BOS       2019   
17  604                 Ty Jerome       Virginia     PHI       2019   
18  605             Nassir Little            UNC     POR       2019   
19  606             Dylan Windler        Belmont     CLE       2019   

    DraftPick  RankedNCAATeam  
0           1               1  
1           3               1  
2           4               1  
3           5               0  
4           6               1  
5           7               0  
6           8               0  
7           9               1  
8          11               0  
9          12               1  
10         13               1  
11         14               0  
12         16               1  
13         17               1  
14         20               0  
15         21               1  
16         22               1  
17         24               1  
18         25               0  
19         26               0

In [6]:
stats['Pos'] = stats['Pos'].map( {'PF': 0, 'SF': 1, 'C': 2, 'PG': 3, 'SG': 4, 'C-': 2} ).astype(int)

In [7]:
standard.isnull().sum()

Unnamed: 0    0
ID            0
Name          0
College       0
NBATeam       0
DraftYear     0
DraftPick     0
G             0
MP            0
FG            0
FGA           0
FGP           0
P2            0
P2A           0
P2P           0
P3            0
P3A           0
P3P           0
FT            0
FTA           0
FTP           0
TRB           0
AST           0
STL           0
BLK           0
TOV           0
PF            0
PTS           0
SOS           0
NBATRB        0
NBAAST        0
NBASTL        0
NBABLK        0
NBAPTS        0
DraftRange    0
Pos.C         0
Pos.PF        0
Pos.PG        0
Pos.SF        0
Pos.SG        0
dtype: int64

In [8]:
stats.head()

Unnamed: 0             Name      School    G    MP   FG   FGA    FG%   2P  \
0           0    Kenyon Martin  Cincinnati  116  23.7  4.4   7.5  0.586  4.4   
1           1   Stromile Swift         LSU   50  26.6  5.1   9.0  0.560  4.9   
2           2     Marcus Fizer  Iowa State   97  32.9  7.1  13.9  0.511  6.9   
3           3      Mike Miller     Florida   65  26.7  4.5   9.2  0.483  3.3   
4           4  DerMarr Johnson  Cincinnati   32  27.5  4.4   9.2  0.478  2.8   

    2PA  ...   SOS  NBATRB  NBAAST  NBASTL  NBABLK  NBAPTS  Pk   Tm  Year  Pos  
0   7.5  ...  6.65     7.4     1.9     1.1     1.7    12.0   1  NJN  2000    0  
1   8.4  ...  5.84     3.6     0.4     0.8     1.0     4.9   2  VAN  2000    0  
2  13.2  ...  6.27     4.3     1.1     0.4     0.3     9.5   4  CHI  2000    0  
3   5.8  ...  7.07     4.0     1.7     0.6     0.2    11.9   5  ORL  2000    1  
4   4.8  ...  8.50     2.3     0.8     0.6     0.4     5.1   6  ATL  2000    1  

[5 rows x 34 columns]

In [9]:
d = {range(1, 11): 1, range(11, 21): 2, range(21, 31): 3,range(31, 41): 4,range(41, 51): 5,
     range(51, 61): 6}

standard['DraftRange'] = standard['DraftPick'].apply(lambda x: next((v for k, v in d.items() if x in k), 0))

For this, value 1 for DraftRange is Top 10, 2 is Top 20 and 3 is the Top 30, 4 is Top 40 and so on. These are the categories that will be used in the classification model.

In [10]:
standard.tail(30)

Unnamed: 0   ID                    Name                College NBATeam  \
606         607  607       Mfiondu Kabengele          Florida State     BRK   
607         608  608            Jordan Poole               Michigan     GSW   
608         609  609          Keldon Johnson               Kentucky     SAS   
609         610  610         Nicolas Claxton                Georgia     BRK   
610         611  611          Carsen Edwards                 Purdue     PHI   
611         612  612          Bruno Fernando               Maryland     PHI   
612         613  613             Cody Martin                 Nevada     CHO   
613         614  614          Daniel Gafford               Arkansas     CHI   
614         615  615            Justin James           Sacred Heart     SAC   
615         616  616           Eric Paschall              Villanova     ATL   
616         617  617       Admiral Schofield              Tennessee     ATL   
617         618  618           Jaylen Nowell             Washington     MIN   
618         619  619                 Bol Bol                 Oregon     PHI   
619         620  620             Isaiah Roby               Nebraska     DET   
620         621  621     Talen Horton-Tucker             Iowa State     ORL   
621         622  622        Ignas Brazdeikis               Michigan     SAC   
622         623  623            Terance Mann          Florida State     LAC   
623         624  624  Quinndary Weatherspoon      Mississippi State     SAS   
624         625  625        Jarrell Brantley  College of Charleston     IND   
625         626  626          Tremont Waters                    LSU     BOS   
626         627  627         Jalen McDaniels        San Diego State     CHO   
627         628  628   Justin Wright-Foreman                Hofstra     UTA   
628         629  629           Marial Shayok             Iowa State     PHI   
629         630  630                Kyle Guy               Virginia     NYK   
630         631  631            Jaylen Hands                   UCLA     LAC   
631         632  632             Jordan Bone              Tennessee     NOP   
632         633  633                Miye Oni                   Yale     GSW   
633         634  634             Cam Reddish                   Duke     ATL   
634         635  635          Kevin PorterJr                    USC     MIL   
635         636  636               Ja Morant           Murray State     MEM   

     DraftYear  DraftPick         G        MP        FG  ...  NBAAST  NBASTL  \
606       2019         27  0.448980  0.401198  0.333333  ...     0.0     0.0   
607       2019         28  0.476190  0.532934  0.287356  ...     0.0     0.0   
608       2019         29  0.217687  0.772455  0.459770  ...     0.0     0.0   
609       2019         31  0.408163  0.541916  0.252874  ...     0.0     0.0   
610       2019         33  0.700680  0.733533  0.609195  ...     0.0     0.0   
611       2019         34  0.401361  0.643713  0.448276  ...     0.0     0.0   
612       2019         36  0.442177  0.904192  0.494253  ...     0.0     0.0   
613       2019         38  0.421769  0.616766  0.574713  ...     0.0     0.0   
614       2019         40  0.598639  0.269461  0.149425  ...     0.0     0.0   
615       2019         41  0.714286  0.727545  0.390805  ...     0.0     0.0   
616       2019         42  0.863946  0.598802  0.436782  ...     0.0     0.0   
617       2019         43  0.442177  0.856287  0.620690  ...     0.0     0.0   
618       2019         44  0.027211  0.745509  0.873563  ...     0.0     0.0   
619       2019         45  0.625850  0.568862  0.264368  ...     0.0     0.0   
620       2019         46  0.204082  0.667665  0.436782  ...     0.0     0.0   
621       2019         47  0.217687  0.739521  0.517241  ...     0.0     0.0   
622       2019         48  0.918367  0.628743  0.344828  ...     0.0     0.0   
623       2019         49  0.857143  0.787425  0.551724  ...     0.0     0.0   
624       2019         50  0.802721

In [11]:
print(np.unique(standard['DraftRange'], return_counts=True))
print(np.unique(standard['DraftPick'], return_counts=True))

(array([1, 2, 3, 4, 5, 6]), array([139, 130, 114, 112,  88,  53]))
(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60]), array([14, 12, 13, 14, 13, 12, 16, 15, 15, 15, 14, 12, 15, 17, 11, 12, 12,
       13, 13, 11, 15, 15, 11, 12, 11, 12,  7, 10, 13,  8,  9, 10, 14, 15,
       11,  6, 10, 17,  9, 11, 10, 10,  8,  9, 12,  9,  7,  7,  7,  9,  4,
        8,  7,  7,  7,  6,  1,  6,  1,  6]))


Next step will be dropping the values that will not be used in predicting the draft.

In [12]:
x = standard.drop(['ID','Name', 'NBATeam', 'DraftPick', 'Unnamed: 0','NBATRB','NBAAST','NBASTL','NBABLK','NBAPTS','College','DraftYear','DraftRange'], axis = 1)
y = standard['DraftRange']

x_1 = standard[['PTS','MP','FGP','SOS']]
y_1 = standard['DraftRange']

I also attempted to use just 4 categories to predict the outcome shown in x_1, for the rest of notebook the models using just the four stats (Points, Minutes Played, Field Goal Percentage and Strength of Schedule) will have a 1 at the end.

In [13]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2,stratify = y)
x_train1, x_test1, y_train1, y_test1 = train_test_split(x_1, y_1, test_size = 0.2,stratify = y_1)

In [14]:
print(np.unique(y_train, return_counts=True))
print(np.unique(y_test, return_counts=True))

(array([1, 2, 3, 4, 5, 6]), array([111, 104,  91,  90,  70,  42]))
(array([1, 2, 3, 4, 5, 6]), array([28, 26, 23, 22, 18, 11]))


## K Nearest Neighbors

In [15]:
from sklearn.neighbors import KNeighborsClassifier
model_KNN = KNeighborsClassifier(n_neighbors=7)
model_KNN.fit(x_train, y_train)
y_testKNN =model_KNN.predict(x_test)
print(classification_report(y_test, y_testKNN, labels=[1, 2, 3, 4, 5, 6]))

              precision    recall  f1-score   support

           1       0.34      0.39      0.37        28
           2       0.18      0.23      0.20        26
           3       0.19      0.22      0.20        23
           4       0.04      0.05      0.04        22
           5       0.09      0.06      0.07        18
           6       0.00      0.00      0.00        11

    accuracy                           0.19       128
   macro avg       0.14      0.16      0.15       128
weighted avg       0.17      0.19      0.18       128



Now only using the four stats to predict draft range

In [16]:
from sklearn.neighbors import KNeighborsClassifier
model_KNN1 = KNeighborsClassifier(n_neighbors=12)
model_KNN1.fit(x_train1, y_train1)
y_testKNN1 =model_KNN1.predict(x_test1)
print(classification_report(y_test, y_testKNN1, labels=[1, 2, 3, 4, 5, 6]))

              precision    recall  f1-score   support

           1       0.23      0.43      0.30        28
           2       0.28      0.31      0.29        26
           3       0.27      0.17      0.21        23
           4       0.29      0.32      0.30        22
           5       0.00      0.00      0.00        18
           6       0.00      0.00      0.00        11

    accuracy                           0.24       128
   macro avg       0.18      0.20      0.18       128
weighted avg       0.20      0.24      0.21       128



In [17]:
accuracyKNN = np.mean(np.where(y_testKNN==y_test,1,0))
print(accuracyKNN)

accuracyKNN1 = np.mean(np.where(y_testKNN1==y_test1,1,0))
print(accuracyKNN1)

0.1875
0.2265625


## Random Forest

In [18]:
model_RF = RandomForestClassifier(n_estimators = 400, max_depth = 40)
_ = model_RF.fit(x_train,y_train)

y_testRF = model_RF.predict(x_test)
print(classification_report(y_test, y_testRF, labels=[1, 2, 3, 4, 5, 6]))

              precision    recall  f1-score   support

           1       0.33      0.36      0.34        28
           2       0.19      0.23      0.21        26
           3       0.20      0.22      0.21        23
           4       0.19      0.23      0.20        22
           5       0.17      0.11      0.13        18
           6       0.50      0.09      0.15        11

    accuracy                           0.23       128
   macro avg       0.26      0.21      0.21       128
weighted avg       0.25      0.23      0.22       128



Now the Random Forest model using only 4 stats to predict draft range.

In [19]:
model_RF1 = RandomForestClassifier(n_estimators = 400, max_depth = 40)
_ = model_RF1.fit(x_train1,y_train1)

y_testRF1 = model_RF1.predict(x_test1)
print(classification_report(y_test, y_testRF1, labels=[1, 2, 3, 4, 5, 6]))

              precision    recall  f1-score   support

           1       0.25      0.32      0.28        28
           2       0.27      0.27      0.27        26
           3       0.19      0.17      0.18        23
           4       0.19      0.23      0.20        22
           5       0.10      0.06      0.07        18
           6       0.25      0.18      0.21        11

    accuracy                           0.22       128
   macro avg       0.21      0.20      0.20       128
weighted avg       0.21      0.22      0.21       128



In [20]:
accuracyRF = np.mean(np.where(y_testRF==y_test,1,0))
print(accuracyRF)

accuracyRF1 = np.mean(np.where(y_testRF1==y_test1,1,0))
print(accuracyRF1)

0.2265625
0.2109375


## Decision Tree

In [21]:
from sklearn.tree import DecisionTreeClassifier

In [22]:
model_DT = DecisionTreeClassifier(max_depth=4)
_ = model_DT.fit(x_train, y_train)

y_testDT = model_DT.predict(x_test)
print(classification_report(y_test, y_testDT, labels=[1, 2, 3, 4, 5, 6]))

              precision    recall  f1-score   support

           1       0.35      0.68      0.46        28
           2       0.39      0.27      0.32        26
           3       0.19      0.17      0.18        23
           4       0.10      0.09      0.09        22
           5       0.40      0.22      0.29        18
           6       0.25      0.09      0.13        11

    accuracy                           0.29       128
   macro avg       0.28      0.25      0.25       128
weighted avg       0.28      0.29      0.27       128



Just the 4 stats to predict draft range

In [23]:
model_DT1 = DecisionTreeClassifier(max_depth=7)
_ = model_DT1.fit(x_train1, y_train1)

y_testDT1 = model_DT1.predict(x_test1)
print(classification_report(y_test, y_testDT1, labels=[1, 2, 3, 4, 5, 6]))

              precision    recall  f1-score   support

           1       0.33      0.57      0.42        28
           2       0.30      0.42      0.35        26
           3       0.20      0.09      0.12        23
           4       0.08      0.09      0.08        22
           5       0.00      0.00      0.00        18
           6       0.50      0.09      0.15        11

    accuracy                           0.25       128
   macro avg       0.23      0.21      0.19       128
weighted avg       0.22      0.25      0.21       128



In [24]:
accuracyDT = np.mean(np.where(y_testDT==y_test,1,0))
print(accuracyDT)

accuracyDT1 = np.mean(np.where(y_testDT1==y_test1,1,0))
print(accuracyDT1)

0.2890625
0.2109375


## SVC

In [25]:
from sklearn.svm import SVC

In [26]:
svc_model=SVC()

In [27]:
svc_model.fit(x_train,y_train)
y_testSVC = svc_model.predict(x_test)
print(classification_report(y_test, y_testSVC, labels=[1, 2, 3, 4, 5, 6]))
accuracySVC = np.mean(np.where(y_testSVC==y_test,1,0))
print(accuracySVC)

              precision    recall  f1-score   support

           1       0.42      0.54      0.47        28
           2       0.25      0.46      0.32        26
           3       0.29      0.22      0.25        23
           4       0.22      0.27      0.24        22
           5       0.00      0.00      0.00        18
           6       0.00      0.00      0.00        11

    accuracy                           0.30       128
   macro avg       0.20      0.25      0.21       128
weighted avg       0.23      0.30      0.26       128

0.296875


/Users/ericcowan/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [28]:
svc_model1=SVC()
svc_model1.fit(x_train1,y_train1)
y_testSVC1 = svc_model1.predict(x_test1)
print(classification_report(y_test, y_testSVC1, labels=[1, 2, 3, 4, 5, 6]))

              precision    recall  f1-score   support

           1       0.30      0.57      0.39        28
           2       0.12      0.12      0.12        26
           3       0.00      0.00      0.00        23
           4       0.26      0.45      0.33        22
           5       0.00      0.00      0.00        18
           6       0.00      0.00      0.00        11

    accuracy                           0.23       128
   macro avg       0.11      0.19      0.14       128
weighted avg       0.13      0.23      0.17       128



/Users/ericcowan/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [29]:
accuracySVC = np.mean(np.where(y_testSVC==y_test,1,0))
print(accuracySVC)

accuracySVC1 = np.mean(np.where(y_testSVC1==y_test1,1,0))
print(accuracySVC1)

0.296875
0.2421875


The best model from this was tied between the SVC Model and KNN Model, both using all stats. I will now look at all of the confusion matrices to determine in what ways each model was wrong. Ideally we are looking for a relatively balanced prediction.

In [30]:
from sklearn.metrics import confusion_matrix

In [31]:
print(y_testRF1)

[1 4 1 6 3 3 3 2 4 1 4 2 4 1 2 1 3 3 4 1 3 4 3 3 1 1 4 4 2 6 5 1 5 2 5 5 1
 4 6 5 1 6 4 1 2 2 4 6 1 1 2 4 3 4 1 6 2 4 5 3 3 1 1 2 3 2 1 1 4 3 4 3 1 4
 2 1 1 2 4 3 2 5 1 1 5 6 2 3 4 2 4 4 2 1 4 2 4 5 2 1 4 1 1 2 2 2 1 3 1 3 1
 2 1 2 3 1 1 5 2 4 1 3 2 4 3 4 1 6]


In [32]:
conf_matrRF = confusion_matrix(y_test,y_testRF)
print(conf_matrRF)

[[10 10  4  3  1  0]
 [ 7  6  5  6  2  0]
 [ 3  7  5  4  3  1]
 [ 5  5  5  5  2  0]
 [ 3  1  5  7  2  0]
 [ 2  3  1  2  2  1]]


In [33]:
conf_matrRF1 = confusion_matrix(y_test1,y_testRF1)
print(conf_matrRF1)

[[12  5  5  4  0  2]
 [ 8  3  6  4  4  1]
 [ 7  5  5  2  2  2]
 [ 5  4  3  6  3  1]
 [ 4  5  1  5  1  2]
 [ 0  4  1  6  0  0]]


In [34]:
conf_matrDT = confusion_matrix(y_test,y_testDT)
print(conf_matrDT)

[[19  4  1  4  0  0]
 [ 9  7  2  5  2  1]
 [10  2  4  6  0  1]
 [ 8  2  7  2  2  1]
 [ 5  2  5  2  4  0]
 [ 3  1  2  2  2  1]]


In [35]:
conf_matrDT1 = confusion_matrix(y_test1,y_testDT1)
print(conf_matrDT1)

[[14  6  2  6  0  0]
 [11  8  3  2  1  1]
 [10  4  1  7  0  1]
 [ 8  6  1  4  3  0]
 [ 4  8  2  4  0  0]
 [ 2  5  1  3  0  0]]


In [36]:
conf_matrSVC = confusion_matrix(y_test,y_testSVC)
print(conf_matrSVC)

[[15  7  3  3  0  0]
 [ 7 12  1  6  0  0]
 [ 6  8  5  4  0  0]
 [ 7  5  4  6  0  0]
 [ 0 10  3  5  0  0]
 [ 1  6  1  3  0  0]]


This SVC model does not predict any in range 5 or 6, which is not balanced.

In [37]:
conf_matrSVC1 = confusion_matrix(y_test1,y_testSVC1)
print(conf_matrSVC1)

[[17  4  1  6  0  0]
 [14  5  3  4  0  0]
 [10  6  1  5  1  0]
 [ 6  6  2  8  0  0]
 [ 5  3  2  8  0  0]
 [ 2  2  0  7  0  0]]


In [38]:
conf_matrKNN = confusion_matrix(y_test,y_testKNN)
print(conf_matrKNN)

[[11  6  2  3  4  2]
 [ 8  6  5  6  1  0]
 [ 3  8  5  5  1  1]
 [ 8  2  8  1  3  0]
 [ 2  6  3  6  1  0]
 [ 0  5  3  2  1  0]]


This KNN model is more balanced than the SVC model that had the same accuracy.

In [39]:
conf_matrKNN1 = confusion_matrix(y_test1,y_testKNN1)
print(conf_matrKNN1)

[[15  6  3  4  0  0]
 [11  5  5  5  0  0]
 [10  6  1  5  1  0]
 [ 8  4  3  4  2  1]
 [ 6  6  1  1  4  0]
 [ 2  2  2  5  0  0]]


In [40]:
print(y_testKNN)

[2 5 3 3 2 1 4 1 4 4 1 2 5 5 2 3 4 4 3 5 6 2 2 2 5 3 2 3 4 2 2 2 1 4 2 2 4
 4 2 4 2 3 5 1 4 2 4 1 1 2 1 3 2 5 3 4 2 3 2 1 1 4 1 1 3 2 3 1 4 1 2 6 3 1
 4 3 4 1 1 4 2 5 2 2 3 1 1 2 2 2 2 1 2 3 5 1 4 5 3 1 6 4 1 3 1 3 3 1 3 3 4
 3 2 3 1 1 1 2 1 5 1 1 4 3 2 3 1 4]


In [41]:
print(y_testSVC)

[2 3 3 2 2 1 4 2 4 2 4 2 4 2 2 2 2 3 2 1 4 2 2 2 3 2 2 3 4 2 4 2 1 3 1 4 4
 3 2 1 4 2 4 2 4 2 3 1 1 2 2 1 2 3 3 4 2 4 4 1 1 2 1 1 1 2 4 1 4 1 1 1 2 1
 4 1 2 1 1 3 2 1 1 2 4 1 2 2 2 1 2 1 2 2 1 1 2 4 4 2 2 3 1 4 3 3 2 1 2 4 4
 4 2 3 1 1 1 2 1 3 1 1 2 4 2 2 3 4]


In [42]:
y_testKNNFinal = model_KNN.predict(x)
accuracyKNNFinal = np.mean(np.where(y_testKNNFinal==y,1,0))
print(accuracyKNNFinal)

0.37735849056603776


In [43]:
print(classification_report(y, y_testKNNFinal, labels=[1, 2, 3, 4, 5, 6]))

              precision    recall  f1-score   support

           1       0.46      0.61      0.52       139
           2       0.35      0.49      0.41       130
           3       0.32      0.32      0.32       114
           4       0.34      0.27      0.30       112
           5       0.40      0.19      0.26        88
           6       0.32      0.13      0.19        53

    accuracy                           0.38       636
   macro avg       0.36      0.34      0.33       636
weighted avg       0.37      0.38      0.36       636



In [44]:
y_testSVCFinal = svc_model.predict(x)
print(classification_report(y, y_testSVCFinal, labels=[1, 2, 3, 4, 5, 6]))

              precision    recall  f1-score   support

           1       0.46      0.61      0.53       139
           2       0.30      0.52      0.38       130
           3       0.27      0.23      0.25       114
           4       0.32      0.36      0.34       112
           5       0.43      0.03      0.06        88
           6       0.00      0.00      0.00        53

    accuracy                           0.35       636
   macro avg       0.30      0.29      0.26       636
weighted avg       0.33      0.35      0.31       636



/Users/ericcowan/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
